# Railway configuration for UniFarm Connect v1.0.33 - SPA FALLBACK FIX
# BACK TO WORKING STATE: Direct tsx execution without Docker
[build]
builder = "nixpacks"

[deploy]
startCommand = "tsx server/simple.ts"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Build configuration
[build.envs]
NODE_ENV = "production" 