# Railway configuration for UniFarm Connect v1.0.35 - FORCE RESTART WITH ENV
# FORCE RESTART: Main server with proper environment variables
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && NODE_ENV=production PORT=3000 tsx server/index.ts"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
FORCE_RESTART = "2025-08-08-14-15"
BUILD_VERSION = "1.0.35"

# Build configuration
[build.envs]
NODE_ENV = "production" 