# Railway configuration for UniFarm Connect v1.0.34 - FORCE RESTART
# FORCE RESTART: Simple server for testing
[build]
builder = "nixpacks"

[deploy]
startCommand = "tsx server/simple.ts"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
FORCE_RESTART = "2025-08-08-13-55"

# Build configuration
[build.envs]
NODE_ENV = "production" 