# Railway configuration for UniFarm Connect v1.0.36 - EMERGENCY RESTART
# EMERGENCY: Force new deployment with different configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && echo 'BUILD COMPLETED' && NODE_ENV=production PORT=3000 tsx server/emergency.ts"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
FORCE_RESTART = "2025-08-08-14-25"
BUILD_VERSION = "1.0.36"
EMERGENCY_MODE = "true"

# Build configuration
[build.envs]
NODE_ENV = "production" 