# Railway configuration for UniFarm Connect v1.0.6
# Clean configuration for new project
[build]
builder = "dockerfile"

[deploy]
startCommand = "tsx server/index.ts"
healthcheckPath = "/api/v2/monitor/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Build configuration
[build.envs]
NODE_ENV = "production" 