# Railway configuration for UniFarm Connect v1.0.38 - PORT FIX
# FIX: Proper port handling for Railway deployment

[build]
# Используем Dockerfile, поэтому builder не нужен

[deploy]
# При Dockerfile Railway использует CMD из образа
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
FORCE_RESTART = "2025-08-08-15-30"
BUILD_VERSION = "1.0.38"
VITE_FIX = "true"
PORT_FIX = "true"

# Build configuration
[build.envs]
NODE_ENV = "production" 