# Railway configuration for UniFarm Connect v1.0.3
[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v2/monitor/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Build configuration
[build.envs]
NODE_ENV = "production" 