# Railway configuration for UniFarm Connect v1.0.5
# Using custom Dockerfile to bypass cache issues
[build]
builder = "dockerfile"
dockerfile = "Dockerfile.railway"

[deploy]
startCommand = "tsx server/index.ts"
healthcheckPath = "/api/v2/monitor/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

# Build configuration
[build.envs]
NODE_ENV = "production" 