[workflow]
name = "Production Server"
author = "UniFarm"
language = "nodejs"

[workflow.metadata]
description = "Stable production server for UniFarm Telegram Mini App"

[[workflow.tasks]]
name = "start"
command = "node production-server.js"
directory = ""
restartOn = [
  "**/*.js",
  "**/*.ts",
  "**/*.json",
  "!node_modules/**",
  "!**/node_modules/**"
]