[nix]
channel = "stable-23_11"

[deployment]
run = ["node", "start.cjs"]
deploymentTarget = "cloudrun"

[github]
silent = true

[languages]

[languages.javascript]
pattern = "**/{*.js,*.jsx,*.ts,*.tsx}"

[languages.javascript.languageServer]
start = "typescript-language-server --stdio"

[languages.typescript]
pattern = "**/{*.ts,*.tsx}"
syntax = "typescript"

[languages.typescript.languageServer]
start = "typescript-language-server --stdio"

[env]
NODE_ENV = "production"
PORT = "3000"
HOST = "0.0.0.0"
SKIP_TELEGRAM_CHECK = "true"
ALLOW_BROWSER_ACCESS = "true"
SKIP_PROCESS_EXIT = "true"
ALLOW_MEMORY_FALLBACK = "true"
DISABLE_PARTITION_CHECK = "true"
IGNORE_DB_CONNECTION_ERRORS = "true"

[unitTest]
language = "nodejs"

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[phases.setup]
cmds = [
  "npm ci"
]