[nix]
channel = "stable-23_11"

[deployment]
run = ["node", "start.cjs"]
deploymentTarget = "cloudrun"

[github]
silent = true

[env]
NODE_ENV = "production"
PORT = "3000"
HOST = "0.0.0.0"
SKIP_TELEGRAM_CHECK = "true"
ALLOW_BROWSER_ACCESS = "true"
SKIP_PROCESS_EXIT = "true"
ALLOW_MEMORY_FALLBACK = "true"
DISABLE_PARTITION_CHECK = "true"
IGNORE_DB_CONNECTION_ERRORS = "true"